In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
  


In [2]:
x=np.array([["France",None,"72000"],["Spain", "78","90000"],["Germany","87",None],["Spain","67","67000"],["France",None,"45000"],["Germany","98","80000"],["Spain",None,"75000"],["France",None,"69000"],["Germany","75","81000"],["Spain",None,"89000"]])
print(x)
y=np.array(["No", "Yes", "No", "Yes", "Yes", "No","Yes","No", "Yes", "No"])
y

[['France' None '72000']
 ['Spain' '78' '90000']
 ['Germany' '87' None]
 ['Spain' '67' '67000']
 ['France' None '45000']
 ['Germany' '98' '80000']
 ['Spain' None '75000']
 ['France' None '69000']
 ['Germany' '75' '81000']
 ['Spain' None '89000']]


array(['No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'],
      dtype='<U3')

#from sklearn.impute import SimpleImputer (thay thế những ô dl trống)

from sklearn.preproccessing import LabelEncoder (biến đỗi những dl danh mục thành dang số học)

from sklearn.model_selection import train_test_split (tách dataset thành training set and test set)

from sklearn.preprpccessing import StandardScaler (chuyển dl thành 1 thang )

In [3]:
from sklearn.impute import SimpleImputer

imputer= SimpleImputer(missing_values=np.nan, strategy="mean")

imputer.fit(x[:,1:3])

x[:,1:3]= imputer.transform(x[:,1:3])

x

array([['France', 81.0, 72000.0],
       ['Spain', 78.0, 90000.0],
       ['Germany', 87.0, 74222.22222222222],
       ['Spain', 67.0, 67000.0],
       ['France', 81.0, 45000.0],
       ['Germany', 98.0, 80000.0],
       ['Spain', 81.0, 75000.0],
       ['France', 81.0, 69000.0],
       ['Germany', 75.0, 81000.0],
       ['Spain', 81.0, 89000.0]], dtype=object)

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct= ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])], remainder="passthrough")

x= ct.fit_transform(x)

x


array([[1.0, 0.0, 0.0, 81.0, 72000.0],
       [0.0, 0.0, 1.0, 78.0, 90000.0],
       [0.0, 1.0, 0.0, 87.0, 74222.22222222222],
       [0.0, 0.0, 1.0, 67.0, 67000.0],
       [1.0, 0.0, 0.0, 81.0, 45000.0],
       [0.0, 1.0, 0.0, 98.0, 80000.0],
       [0.0, 0.0, 1.0, 81.0, 75000.0],
       [1.0, 0.0, 0.0, 81.0, 69000.0],
       [0.0, 1.0, 0.0, 75.0, 81000.0],
       [0.0, 0.0, 1.0, 81.0, 89000.0]], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0])

In [6]:
from sklearn.model_selection import train_test_split
np.random.seed(40)
x_train, x_test, y_train, y_test=train_test_split(x,y , test_size=0.2)

x_train

array([[0.0, 1.0, 0.0, 75.0, 81000.0],
       [0.0, 0.0, 1.0, 78.0, 90000.0],
       [0.0, 1.0, 0.0, 87.0, 74222.22222222222],
       [0.0, 0.0, 1.0, 81.0, 89000.0],
       [1.0, 0.0, 0.0, 81.0, 72000.0],
       [0.0, 1.0, 0.0, 98.0, 80000.0],
       [1.0, 0.0, 0.0, 81.0, 69000.0],
       [0.0, 0.0, 1.0, 81.0, 75000.0]], dtype=object)

In [10]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_train

array([[0.0, 1.0, 0.0, -1.1792955782082268, 0.3091223338675927],
       [0.0, 0.0, 1.0, -0.7227940640631069, 1.5610677860313449],
       [0.0, 1.0, 0.0, 0.6467104783722535, -0.6337007844285668],
       [0.0, 0.0, 1.0, -0.26629254991798673, 1.4219627357909281],
       [1.0, 0.0, 0.0, -0.26629254991798673, -0.9428231182961595],
       [0.0, 1.0, 0.0, 2.3205493635710273, 0.17001728362717577],
       [1.0, 0.0, 0.0, -0.26629254991798673, -1.3601382690174102],
       [0.0, 0.0, 1.0, -0.26629254991798673, -0.5255079675749088]],
      dtype=object)